version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "{{s3_bucket_url}}"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        nodejs: 14
    commands:
        - echo Installing source NPM dependencies...
        - npm install --global yarn
        - yarn install
  build:
    commands:
        - echo Creating env file from aws parameters
        - echo AWS_BUCKET_NAME = $AWS_BUCKET_NAME
        - echo start hardhat compile
        - npx hardhat compile
        - echo Build started 
        - yarn run build
artifacts:
    files:
        - '**/*'
    base-directory: './dist*'
    discard-paths: yes