version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "{{s3_bucket_url}}"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        nodejs: 14
    commands:
        - echo Installing source NPM dependencies...
        - npm install --global yarn
        - yarn install
  build:
    commands:
        - echo Creating env file from aws parameters
        - echo AWS_BUCKET_NAME = $AWS_BUCKET_NAME
        - echo "ETHERS_USE_LOCAL = 1" >> .env
        - echo "ADSBOARD_CONTRACT = $ADSBOARD_CONTRACT" >> .env
        - echo "ETHEREUM_WALLET_MNEMONIC = $ETHEREUM_WALLET_MNEMONIC" >> .env
        - echo "AWS_BUCKET_NAME = $AWS_BUCKET_NAME" >> .env
        - echo "AWS_BUCKET_REGION = $AWS_BUCKET_REGION" >> .env
        - echo "AWS_SECRET_ACCESS_KEY = $AWS_SECRET_ACCESS_KEY" >> .env
        - echo "AWS_ACCESS_KEY_ID = $AWS_ACCESS_KEY_ID" >> .env
        - echo Show file content
        - less .env
        - echo going inside ethereum
        - cd ethereum
        - echo Creating env file from aws parameters
        - echo "ETHERSCAN_API_KEY = ABC123ABC123ABC123ABC123ABC123ABC1" >> .env
        - echo "ROPSTEN_URL=" >> .env
        - echo "PRIVATE_KEY = $PRIVATE_KEY" >> .env
        - echo "RINKEBY_URL = $RINKEBY_URL" >> .env
        - echo "RINKEBY_MNEMONIC = $RINKEBY_MNEMONIC" >> .env
        - echo Show file content
        - less .env
        - echo start hardhat compile
        - npx hardhat compile
        - cd ..
        - echo Build started 
        - yarn run build
artifacts:
    files:
        - '**/*'
    base-directory: './dist*'
    discard-paths: yes